export const LOGGIN = "LOGGIN";
export const LOGGIN_SUCCESS = "LOGGIN_SUCCESS";
export const LOGGIN_FAILED = "LOGGIN_FAILED";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

// Department type
// export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
// export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
// export const FETCH_DEPARTMENT_FAILED = "FETCH_DEPARTMENT_FAILED";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_ALL_DEPARTMENT = "GET_ALL_DEPARTMENT";
export const POST_DEPARTMENT = "POST_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
// Employee type
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const POST_EMPLOYEE = "POST_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

//Pagination
export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";
export const LOADING_EMPLOYEE_TRUE = "LOADING_EMPLOYEE_TRUE";
export const LOADING_EMPLOYEE_FALSE = "LOADING_EMPLOYEE_FALSE";
